- doc/conf.py
- doc/installation/index.rst
Add instructions to use the new repository adn update instructions to install packages.
Tested installation based on documentation.
> update content with new repository and CentOS7

- doc/release_notes/centreon_clib_19_10.rst
- doc/release_notes/index.rst
> enh(doc): add 19.10 release notes

- src/handle_action.cc
- src/handle_manager.cc
- src/task_manager.cc
Various calls to system() removed (debug calls).
> cleanup(debug): Debug log functions removed.

- CMakeLists.txt
Use the same abi as everywhere for clib.
> fix(chore) use the same abi as everywhere for clib

- src/process_manager.cc
For that a dummy msg sent on the closed pipe do the magic...
This fix the wait for 200ms between each process...
> fix(process): We need to get ou of poll when there is a new fd to watch.

- doc/release_notes/centreon_clib_20_04.rst
- src/process_manager.cc
port of MON-5939-deadlock to 20.10
> fix(process_manager): deadlock removed.

- Jenkinsfile
remove centos6 & debian9 support
> chore(build): remove centos6 & debian9 support

- README.md
- cmake.sh
cmake.sh is better and works also on Debian.
> Build debian

- README.md
- cmake.sh
- deps.go
- deps.sh
- inc/com/centreon/clib.hh
- inc/com/centreon/delayed_delete.hh
- inc/com/centreon/exceptions/basic.hh
- inc/com/centreon/handle_action.hh
- inc/com/centreon/handle_listener.hh
- inc/com/centreon/handle_manager.hh
- inc/com/centreon/logging/logger.hh
- inc/com/centreon/process.hh
- inc/com/centreon/process_manager.hh
- inc/com/centreon/task_manager.hh
- inc/com/centreon/timestamp.hh
- inc/com/centreon/unordered_hash.hh
- src/handle_action.cc
- src/handle_manager.cc
- src/library.cc
- src/process.cc
- src/process_manager.cc
- src/task_manager.cc
- src/timestamp.cc
- test/process_output.cc
Code optimized with several mutexes removed.
> Mon 5939 processes locks

- deps.go
- deps.sh
- doc/release_notes/centreon_clib_20_04.rst
- inc/com/centreon/clib.hh
- inc/com/centreon/delayed_delete.hh
- inc/com/centreon/exceptions/basic.hh
- inc/com/centreon/handle_action.hh
- inc/com/centreon/handle_listener.hh
- inc/com/centreon/handle_manager.hh
- inc/com/centreon/logging/logger.hh
- inc/com/centreon/process.hh
- inc/com/centreon/process_manager.hh
- inc/com/centreon/task_manager.hh
- inc/com/centreon/timestamp.hh
- inc/com/centreon/unordered_hash.hh
- src/handle_action.cc
- src/handle_manager.cc
- src/library.cc
- src/process.cc
- src/process_manager.cc
- src/task_manager.cc
- src/timestamp.cc
- test/process_output.cc
process manager greatly simplified.
timestamp optimized.
process does not share anymore its mutex with the manager.
> Mon 5939 processes locks 20.04

- CHANGELOG.md
- inc/com/centreon/process_listener.hh
- inc/com/centreon/process_manager.hh
- src/process.cc
- src/process_manager.cc
- test/process_wait_timeout.cc
* Deadlocks removed.
* Thread starting optimized.
* Log informations added.
> Mon 6508 engine crash during stop 20.10

- CHANGELOG.md
- inc/com/centreon/process_listener.hh
- inc/com/centreon/process_manager.hh
- src/process.cc
- src/process_manager.cc
- test/process_wait_timeout.cc
Almost the same as MON-6508 engine crash during stop 20.10
> Mon 6508 engine crash during stop 20.04

- inc/com/centreon/process_listener.hh
- inc/com/centreon/process_manager.hh
- src/process.cc
- src/process_manager.cc
- test/process_wait_timeout.cc
back port of MON-6508 on master
> Mon 6508 engine crash during stop

- Jenkinsfile
> fix(ci): fix quality gate timeout

- cmake.sh
- test/CMakeLists.txt
Please include a short resume of the changes and what is the purpose of PR. Any relevant information should be added to help:
* **QA Team** (Quality Assurance) with tests.
* **reviewers** to understand what are the stakes of the pull request.
**Fixes** # (issue)
<h2> How this pull request can be tested ? </h2>
Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.
Any **relevant details** of the configuration to perform the test should be added.
> fix(cmake): compilation repair for debian 11

- CMakeLists.txt
- inc/com/centreon/process.hh
- src/process.cc
- src/process_manager.cc
- test/CMakeLists.txt
- test/process.cc
A deadlock in process between read and write is fixed.
REFS: MON-10980
> Mon 10980 deadlock

- CHANGELOG.md
- cmake.sh
- inc/com/centreon/process.hh
- src/process.cc
- src/process_manager.cc
- test/CMakeLists.txt
- test/process_output_mt.cc
- test/process_output_mt1.cc
A deadlock in processes is fixed.
> Mon 10980 deadlock 21.04

- CHANGELOG.md
- cmake.sh
- inc/com/centreon/process.hh
- src/process.cc
- src/process_manager.cc
- test/CMakeLists.txt
- test/process_output_mt.cc
- test/process_output_mt1.cc
A deadlock in processes is fixed.
> Mon 10980 deadlock 20.10

- CHANGELOG.md
- src/process.cc
- src/process_manager.cc
- test/CMakeLists.txt
- test/process_output_mt.cc
- test/process_output_mt1.cc
> Mon 10980 deadlock 20.04

- .github/workflows/dependabot_jira.yml
Modify Jira ticket created on dependabot PR
**Fixes** # (none)
> enh(chore): issueType, feature_team and issue description
